apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  namespace: laravel-prod
data:
  APP_NAME: K8S-Laravel
  APP_ENV: production
  APP_DEBUG: 'true'
  APP_URL: https://laravel-api.example.com
  DB_HOST: mysql-service
  DB_PORT: '3306'
  DB_CONNECTION: mysql

  APP_LOCALE: 'en'
  APP_FALLBACK_LOCALE: 'en'
  APP_FAKER_LOCALE: 'en_US'

  APP_MAINTENANCE_DRIVER: 'file'
  BCRYPT_ROUNDS: '12'

  LOG_CHANNEL: 'stack'
  LOG_STACK: 'single'
  LOG_DEPRECATIONS_CHANNEL: 'null'
  LOG_LEVEL: 'debug'

  SESSION_LIFETIME: '120'
  SESSION_ENCRYPT: 'false'
  SESSION_PATH: '/'
  SESSION_DOMAIN: 'laravel-api.example.com'
  SESSION_DRIVER: database #file

  BROADCAST_CONNECTION: 'log'
  FILESYSTEM_DISK: 'local'
  QUEUE_CONNECTION: 'database'

  CACHE_STORE: 'database'

  MEMCACHED_HOST: 127.0.0.'1'

  REDIS_CLIENT: 'phpredis'
  REDIS_HOST: redis-service
  REDIS_PASSWORD: 'null'
  REDIS_PORT: '6379'

  MAIL_MAILER: 'log'
  MAIL_SCHEME: 'null'
  MAIL_HOST: 127.0.0.'1'
  MAIL_PORT: '2525'
  MAIL_USERNAME: 'null'
  MAIL_PASSWORD: 'null'
  MAIL_FROM_ADDRESS: 'hello@example.com'
  MAIL_FROM_NAME: K8S-Laravel

  VITE_APP_NAME: K8S-Laravel
