apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: laravel-prod
type: Opaque
stringData:
  APP_KEY: base64:KelLuTNL5IPTi70Ybn2KLLYuPEMyQQ49w+V8RQLuOGw=
  DB_DATABASE: laravel
  DB_USERNAME: laravel_user
  DB_PASSWORD: supersecret
  MYSQL_ROOT_PASSWORD: rootsecret
