apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: laravel-ingressroute
  namespace: laravel-prod
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`laravel-api.example.com`)
      kind: Rule
      services:
        - name: laravel-service
          port: 80
  tls:
    secretName: laravel-api-tls
